### ISSUE TITLE
Package error and need Pro license query

### ISSUE THREAD

**Issue by iambiglee** [eroself/vaadin-litelement-zxing#15]
Hello Ryan
     Thanks for you this open source project, it help me a lot in my project.
     But currently, a package error puzzled me a lot  and I even report to  vaadin/flow#17180. and they don't know too.
     I use the latest version V2.0.2-8 too, it still has License Check error

**Comment by eroself** [comment]
I have no idea what happened. Make sure you cleaned your workspace throughly after maven configuration changes, manually delete target and node_modules folder and all .class files.

**Comment by iambiglee** [comment]
According to the vaadin team, it is seem like license checking has been changed since flow 2.8.0 (Vaadin 14.9.0), it has been described in the flow release note, https://github.com/vaadin/flow/releases/tag/2.8.0.

consider that vaadin 14 LTS will be end next year, I think upgrade vaadin from 14 to 23 is batter idea for my team
